name: Build C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Set up build environment
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw -y
          
      - name: Set up build environment
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc
          
      - name: Compile bsharp.cpp
        if: matrix.os == 'ubuntu-latest'
        run: |
            g++ bsharp.cpp -o bsc
            
      - name: Compile bsharp.cpp
        if: matrix.os == 'windows-latest'
        run: |
            g++ bsharp.cpp -o bsc.exe

      - name: Compile bsharp.cpp
        if: matrix.os == 'macos-latest'
        run: |
            g++ bsharp.cpp -o bsc_mac

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bsharp_${{ matrix.os }}
          path: |
            bsc
            bsc_mac
            bsc.exe
